[scoop]
  buckets = [
    "extras",
    "versions",
    "nirsoft",
    "nerd-fonts",
    "java",
    "games",
    # "ks ssh://git@dev.ks.int:7999/tools/tdr.git",
  ]
  packages = [
    "7zip",
    "autohotkey",
    "bat",
    "btop",
    "CascadiaCode-NF",
    "cascadiacode-nf-mono",
    "ccache",
    "cpu-z",
    "cryptomator",
    "delta",
    "diffutils",
    "draw.io",
    "dual-monitor-tools",
    "eza",
    "fd",
    "firefox",
    "FiraCode",
    "FiraCode-NF",
    "FiraCode-NF-Mono",
    "fzf",
    "gh",
    "git",
    "git-credential-manager",
    "glazewm",
    "graphviz",
    "gzip",
    "Hack-NF-Mono",
    "hexyl",
    "Inconsolata-NF",
    "keepassxc",
    "lazygit",
    "libreoffice",
    "llvm",
    "lua",
    # "lua-language-server",
    "luarocks",
    "marp",
    "mattermost",
    "Monoid-NF",
    "neovide",
    "neovim",
    "ninja",
    "nodejs",
    "notepadplusplus",
    "nsis",
    "obsidian",
    "openjdk",
    "openjdk17",
    "openssl",
    "pandoc",
    "patch",
    "pdftk",
    "perl",
    # "pipx",
    "plantuml",
    "pwsh",
    "python",
    "ripgrep",
    "ruby",
    "rufus",
    "rustup",
    "scoop-search",
    "screentogif",
    "sed",
    "shellcheck",
    "spotify",
    "starship",
    "sudo",
    "sumatrapdf",
    "sysinternals",
    # "tlaplus-toolbox",
    "unzip",
    "uv",
    "Ubuntu-NF",
    "UbuntuMono-NF",
    "universal-ctags",
    "vscode",
    "wezterm",
    "wget",
    "windirstat",
    "windows-terminal",
    "xmind",
    "xnview",
    "yazi",
    "zebar",
    "zoxide",
  ]
  su_packages = [
    # "openvpn"
  ]
  hold = [
    "msys2",
  ]

[msys2]
  packages = [
    "diffutils",
    "dos2unix",
    "make",
    "openssh",
    "unzip",
    "zsh",
    "msys/cloc",
    "msys/man-pages-posix",
    "msys/procps-ng",
    "ucrt64/mingw-w64-ucrt-x86_64-gcc",
  ]

# NOTE: 'extras' is a special key to identify packages that should not be
# installed in a WSL2 environment, but should be installed in any other Linux
# environment

[apt]
  base = [
    # "clangd",
    "direnv",
    "exuberant-ctags",
    "gcc",
    "git",
    "ripgrep",
    "zsh",
  ]
  extras = [
    "firefox",
    "flatpak",
    "rclone",
  ]

[brew]
  tap = [
    'wezterm/wezterm-linuxbrew',
  ]
  base = [
    # "bash-language-server",
    "bat",
    "eza",
    "fd",
    "fzf",
    "git-delta",
    # "lua-language-server",
    "neovim",
    "ninja",
    "node",
    # "pipx",
    "plantuml",
    "python",
    "starship",
    "tree-sitter",
    # "typescript-language-server",
    "uv",
    "wezterm/wezterm-linuxbrew/wezterm",
    "zoxide",
  ]
  extras = [
    "neovide",
  ]

[flatpak]
  base = [
  ]
  extras = [
    "com.mattermost.Desktop",
    "it.mijorus.smile",
    "md.obsidian.Obsidian",
    "net.xmind.XMind",
    "org.telegram.desktop",
    "com.jgraph.drawio.desktop",
  ]

[python]
  pip = [
    "rich",
    "colorama",
    "icecream",
  ]

[[python.tool]]
  pkg = "python-lsp-server"
  opt = "[all]"
  python = "3.9"
  deps = [
        "python-lsp-ruff",
        "pylsp-rope",
        "pylsp-mypy",
      ]

[[python.tool]]
  pkg = "notify-py"

[[python.tool]]
  pkg = "meson"

[node]
  npm = [
    # "vim-language-server",
    # "vscode-langservers-extracted",
  ]
  windows = [
    # "bash-language-server",
    "typescript",
    # "typescript-language-server",
  ]
