# additional index (for work)
index-strategy = "unsafe-best-match"
[[index]]
name = "ks"
url = "http://dev.ks.int/store/repository/pypi/simple"
publish-url = "http://dev.ks.int/store/repository/pypi/simple"

# always use system Python interpreter - do not install managed interpreters â€“
# at least for now...
python-preference = "only-system"
